apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gradio-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - name: gradio-app
        image: 'us-docker.pkg.dev/google-samples/containers/gke/gradio-app:v1.0.0'
        ports:
        - name: http1
          containerPort: 7860
        env:
        - name: CONTEXT_PATH
          value: /generate
        - name: HOST
          value: 'http://MODEL_SERVER:8000'
        - name: LLM_ENGINE
          value: tgi
        - name: MODEL_ID
          value: gemma
        - name: USER_PROMPT
          value: <start_of_turn>user\nprompt<end_of_turn>\n
        - name: SYSTEM_PROMPT
          value: <start_of_turn>model\nprompt<end_of_turn>\n
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 7860
  traffic:
  - percent: 100
    latestRevision: true
